### ISSUE TITLE
webpack resolve alias

### ISSUE THREAD

**Issue by chasonma** [ream/ream#105]
目前直接修改了 ream 的 webpack.config.base.js 的配置来定义别名，ream.config.js 配置可以增加别名这块的定义。

**Comment by IlyaSemenov** [comment]
You can add it like this, in `ream.config.js`:

```js
module.exports = {
  plugins: [
    {
      name: 'my:webpack',
      apply (ream) {
        ream.chainWebpack(config => {
          config.merge({
            resolve: {
              alias: {
                '@': path.resolve('src')
              },
            }
          })
        })
      }
    },
  ],
}
```

**Comment by chasonma** [comment]
@IlyaSemenov Think you, but File to import not found or unreadable, @ it doesn't work.

**Comment by IlyaSemenov** [comment]
You may try `console.log(config.toString())` right after `config.merge`, this will print raw webpack config and you could check if the config resolve rules are what you expect or not.

**Comment by chasonma** [comment]
@IlyaSemenov OK, Thanks again, the problem has been found.

**Comment by egoist** [comment]
maybe we should support `configureWebpack` (webpack-merge) and `chainWebpack` (webpack-chain) options in config file, just like vue-cli 3
