### ISSUE TITLE
Reconsider options.dev / process.env.NODE_ENV

### ISSUE THREAD

**Issue by IlyaSemenov** [ream/ream#107]
In the current implementation, I see two problems:

1) Ream constructor writes to `process.env.NODE_ENV`. Architecture wise it's not a good thing as it may give side effects when used in a complex application (when not running `ream` cli in a standalone app but rather creating the app manually via API).
2) When constructing Ream object manually via API, the user is *forced* to copy-paste `dev: process.env.NODE_ENV !== 'production'`

I think it should be the other way around:
* `options.dev` should be allowed not to be provided; and in that case it should be inferred from `process.env.NODE_ENV`. However if `options.dev` is provided, it should be used and `process.env.NODE_ENV` should be ignored.
* Ream should not write to `process.env.NODE_ENV`.
* Ream should not *use* `process.env.NODE_ENV` other than in the app constructor (e.g. in webpack config, in `handleError`, in `pwa` plugin etc.) but rather always rely on `options.dev`.

I would come up with a PR, just let me know if you're still alive ;)

**Comment by Atinux** [comment]
Interesting idea @IlyaSemenov 👍

**Comment by egoist** [comment]
I noticed that some tools will add optimizations when `process.env.NODE_ENV === 'production'` by default:

<img width="883" alt="2018-10-11 2 26 30" src="https://user-images.githubusercontent.com/8784712/46784835-413ff600-cd62-11e8-85b4-229d23aa60c9.png">

Maybe it's fine to set a default value when it's not defined by user?

**Comment by IlyaSemenov** [comment]
I think the CLI command `ream dev/build/generate` could set it indeed, but not the class API that could potentially be used in unpredictably fragile user environment.
