### ISSUE TITLE
Vuex example not listing vuex in package.json

### ISSUE THREAD

**Issue by askcreative** [ream/ream#127]
Where should Vuex be set up at?

I cloned then ran the folder 'examples/prepopulate-vuex' and got the following error. 

ERROR in ./index.js
Module not found: Error: Can't resolve 'vuex' in '/home/snow/GitLab/ream-test/examples/prepopulate-vuex'
 @ ./index.js 3:0-24 5:8-12 7:13-17
 @ ./.ream/entry.js
 @ ./.ream/create-app.js
 @ ./node_modules/ream/app/client-entry.js
 @ multi (webpack)-hot-middleware/client.js ./node_modules/ream/app/client-entry.js

**Comment by IlyaSemenov** [comment]
Please follow the README at https://github.com/ream/ream/blob/master/examples/prepopulate-vuex/README.md

Vuex is not coupled with Ream.

**Comment by IlyaSemenov** [comment]
Oh I see. That example is not listing vuex as a dependency indeed and must be fixed. Please install it manually in the meanwhile (`yarn add vuex`).

**Comment by IlyaSemenov** [comment]
@egoist what do you think about including everything needed for examples (Vuex, apollo, ...) in `devDependencies` and removing individual examples' `package.json`'s? That in particular would allow to add tests for all examples. The drawback is, obviously, having a few extra packages in main `package.json`.

**Comment by IlyaSemenov** [comment]
OK I think it should be both. Individual examples should continue to have their `package.json`'s to be completely functional on their own. However, ream `devDependencies` may indeed list packages like `vuex` for testing.
