### ISSUE TITLE
Disable SSR for some part of code

### ISSUE THREAD

**Issue by SacDin** [ream/ream#129]
Hello

I have some components which are designed to run only in browser. I tried using following
```
if(process.browser) {
  import infiniteScroll from 'vue-infinite-scroll'
  Vue.use(infiniteScroll)
}
```
but got error : import can not be used at top level

For component level, I am using your module vue-no-ssr. Please confirm, Is it designed to work with ream ?

Regards.

**Comment by IlyaSemenov** [comment]
Yes, it is. Actually, vue-no-ssr was created by Ream's author (@egoist).

`import`'s don't work inside `if`'s, you should use `require`:

```js
if (process.client) {
  Vue.use(require('vue-infinite-scroll')) // or require('vue-infinite-scroll').default - depends on package
}
```
