### ISSUE TITLE
is there any guide for deploy and build?

### ISSUE THREAD

**Issue by xurwxj** [ream/ream#135]
how to do it if we want to publish static resource to cdn after build?
is it enough to copy all files except views under project when we deploy to product env after build?
project has follow structure after build:
- .ream
    - client // how to publish to cdn?
    - server
    - create-app.js  // is this file required during running?
    - entry.js   // is this file required during running?
- node_modules
- public   // how to publish to cdn?
- views   // is this directory required during running?
- package.json
- server.js
- index.js

is ream can run with pm2?
how about log for running? is current only support stdout?

**Comment by IlyaSemenov** [comment]
You should only publish `.ream/client/*` to CDN (and then change webpack's `config.output.publicPath` from `/_ream/` to your CDN URL with an ad-hoc plugin).

`public/` should not be published as it's what served under `https://yourproject.com/` directly (e.g. `https://yourproject.com/robots.txt`) and is served by the Ream server directly.

---

`create-app.js`, `entry.js`, `views` are not needed for `ream start`, they are webpacked into server bundle.

---

For pm2: I have mixed results.

```
pm2-docker --auto-exit start npm -- start
```

would work but if I add `-i 2` it will crash in funny ways. Perhaps it needs to be looked into. (@egoist : the same command works for Nuxt.)

---

Logging goes to stdout/stderr only, yes.

**Comment by IlyaSemenov** [comment]
I personally deploy it in Docker and run behind nginx forward-proxy:

```
map $http_upgrade $connection_upgrade {
	default upgrade;
	'' close;
}

proxy_set_header Host $http_host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $connection_upgrade;

server {
	listen 80 default_server;
	client_max_body_size 32M;

	location / {
		proxy_pass http://127.0.0.1:4000;
	}

	location /_ream/ {
		alias /app/.ream/client/;
		expires max;
	}
}
```

Docker build runs `yarn build` and docker entrypoint runs `yarn start`.

**Comment by xurwxj** [comment]
@IlyaSemenov thank you very much. do you keep the .ream/server directory after deploy?
