### ISSUE TITLE
Support deploying to ZEIT Now as serverless function

### ISSUE THREAD

**Issue by egoist** [ream/ream#19]
You can already deploy it as a static site but it seems a bit tricky to deploy as a serverless function. I guess we'll have to create a custom Now builder. We should start this when entering RC phase.

**Comment by MarchWorks** [comment]
Doesn't this need a serverless target build?

**Comment by egoist** [comment]
https://github.com/vercel/vercel/blob/master/DEVELOPING_A_RUNTIME.md

**Comment by egoist** [comment]
It's here https://twitter.com/_egoistlily/status/1367072214432899075
