### ISSUE TITLE
Feature request: Ability to add routes programmatically

### ISSUE THREAD

**Issue by Rusya13** [ream/ream#215]
At the moment we can use a hook `onCreatedApp` in `enchance-app.ts` where we have an access to `app`, `router` and `initiateState`.
If I add a new route using router API (e.g router.addRoute({...})  this route will work only after the application loaded in the browser. So I can go to this new page, and it will be rendered.
But if I reload the page it will give me 404 error. It happens because this hook `onCreatedApp` has not been taken to consideration during SSR.

Thank you for this framework.

**Comment by egoist** [comment]
Yeah `onCreatedApp` is called after we use `router.currentRoute`, will fix it soon.

**Comment by egoist** [comment]
I'll add another hook for it since `router.currentRoute` needs to be resolved before creating the `app`.

**Comment by egoist** [comment]
Actually it might be better to add routes at build time, I've added this as an option in the config file: 

```ts
// ream.config.ts
export default {
  routes(defaultRoutes) {
    return [
      ...defaultRoutes,
      {
        path: '/foo',
        file: path.join(__dirname, './views/Foo.vue'),
      },
      {
        path: '/api',
        file: path.join(__dirname, './server/api.ts'),
        isServerRoute: true,
      },
    ]
  },
}
```

---

An app hook `extendRouter` is also added if you want it: https://ream.dev/docs/references/app-hooks#extendrouter (`enhance-app.ts` is renamed to `ream.app.ts`)
