### ISSUE TITLE
Correctly configuring vue-router for use with ream

### ISSUE THREAD

**Issue by mmajko** [ream/ream#27]
There should be in the documentation a mention of how to configure *vue-router* correctly.

@jnv found out that you have to use the history mode. See https://github.com/cvut/fittable-next/commit/8444947b510d9bf67997b697abaeaf14478ab9b7#diff-15ee858ae5d5aa9b3e2846cfd1c4c466

Without the fix it's not possible to match server-rendered content on client.

**Comment by egoist** [comment]
Ah yes, I should mention this in the docs, and it's recommend to always use `() => import('./path/to/view.vue')` for code-split

**Comment by egoist** [comment]
Doc has been updated for this. https://ream.github.io/ream/#/?id=router-instance
