### ISSUE TITLE
Don't automatically (and opaquely) change the NODE_ENV environment variable

### ISSUE THREAD

**Issue by jazoom** [ream/ream#28]
I am in the process of getting Ream working with an existing server application and I was getting a bunch of errors which I found to be due to my environment variable being changed by this call: `ream()`.

The environment variable used by this project at the moment is `'dev'`. There does not seem to be a way to force `ream()` to allow that. Using `ream({dev: true})` makes `NODE_ENV === 'development'`, which is obviously unhelpful to this particular application.

Perhaps environment variables should be left to the environment to set them?

**Comment by egoist** [comment]
Fixed in `v1.0.0-beta.6`
