### ISSUE TITLE
Automatically add routes for `generate` command

### ISSUE THREAD

**Issue by egoist** [ream/ream#32]
```js
{
  generate: {
    routes: [':static:']
  }
}
```

Use `:static:` keyword so that Ream will add all routes specified in vue-router for you to generate static pages, this is useful when your routes do not contain patterns like `:id` or regexp.

**Comment by qm3ster** [comment]
I would like to add to this that supplying the possible values for dynamic routes (without specifying the routes it applies to, just as lists of values or records) would be even better, something even Nuxt currently doesn't do. This would be particularly useful with the file API for routes.

**Comment by egoist** [comment]
@qm3ster how would the potential API look like? I didn't really get what `supplying the possible values for dynamic routes (without specifying the routes it applies to, just as lists of values or records)` means.

**Comment by qm3ster** [comment]
It's just an idea.

#### By values
```js
{
  generate: {
    routes: ['/', '/user/:name/', '/user/:name/:id/'],
    data: { name: ['egoist', 'trump'], id: [1, 2] } // by values
  }
}
// /
// /user/egoist/
// /user/egoist/1/
// /user/egoist/2/
// /user/trump/
// /user/trump/1/
// /user/trump/2/
```
#### By records
```js
{
  generate: {
    routes: ['/', '/user/:name/:id/'],
    data: [
      {name: 'egoist', id: 1}, 
      {name: 'trump', id: 1}, 
      {name: 'trump', id: 2}
    ] // by records
  }
}
// /
// /user/egoist/1/
// /user/trump/1/
// /user/trump/2/
```
#### Combined with Object routes
```js
{
  generate: {
    routes: {
      '/': true,
      '/user/:name/:id': [
        { name: 'egoist' },
        { name: 'trump' }
      ]
    }
    data: {id: [1, 2] } // by values
  }
}
// /
// /user/egoist/1/
// /user/egoist/2/
// /user/trump/1/
// /user/trump/2/
```
#### Combined with `:static:`
```js
{
  generate: {
    routes: [':static:'], // from router options
    data: { name: ['egoist', 'trump'] } // by values
  }
}
```
