### ISSUE TITLE
404, static files.

### ISSUE THREAD

**Issue by FrancosLab** [ream/ream#37]
I can't seem to load the static files.

Vue File:

`            <img src="/static/img/placeholder.png"/>
`

File Structure

```
- src
- static
    -- img
    --- placeholder.png

```

**Comment by FrancosLab** [comment]
Got it working by renaming the static folder to public. 

Seems the static folder gets copied directly to the `.ream/dist` folder without the `static` folder enclosing, while the public folder, does not get copied and served directly

**Comment by egoist** [comment]
Yep, that's the expected behavior.

**Comment by egoist** [comment]
Hmm, this seems a bit confusing, maybe we can remove `./public` folder support, since using `./static/public` has the same effect.

**Comment by egoist** [comment]
The behavior in `ream@next`:

- `./static/foo` will be served at `/_ream/static/foo` but also available at `/foo`
