### ISSUE TITLE
🥰 Rewriting for Vue 3..

### ISSUE THREAD

**Issue by egoist** [ream/ream#38]
TODOS:

- [x] HELP WANTED: Head management plugin for Vue, like react-helmet and vue-meta, [@ream/head](https://github.com/ream/ream/tree/next/packages/%40ream/head)
- [ ] HELP WANTED: Lightweight Express/Connect alternative, we actually only need the "middleware" functionality. [ream/server](https://github.com/ream/ream/blob/next/packages/ream/src/server/server.ts)
- [x] WIP: `ream export`, exporting pages to static HTML files,  "API pages" are also supported
- [x] WIP: Preloading data using `preload` export on page components
- [ ] ~~WIP: Nested routes #41~~
- [x] Error pages (404 and 500)

**Comment by nblthree** [comment]
For the second checkbox isn't that basically [next-connect](https://github.com/hoangvvo/next-connect/blob/master/lib/index.js )?

**Comment by egoist** [comment]
@nblthree yeah that's what I meant, I also have a naive implementable using `connect` directly right now: https://github.com/ream/ream/blob/master/packages/ream/src/server/server.ts I will soon replace `connect` with a custom implementation.

The long-term goal for Ream is to eliminate the need of using another framework like `AdonisJS` or `NestJS` to build your API / backend, similar to what redwoodjs and blitzjs is doing.

**Comment by varna** [comment]
Vercel got some code for middlewares and helpers that could be useful for `ream/server`:
https://github.com/vercel/vercel/blob/1f0ebcef2421a71c61d1739537298d30ef21dbf1/packages/now-node/src/helpers.ts

Node (req: [http.IncomingMessage](https://nodejs.org/api/http.html#http_class_http_incomingmessage), res: [http.ServerResponse](https://nodejs.org/api/http.html#http_class_http_serverresponse)) gets transformed into Vercel ([NowRequest](https://nextjs.org/docs/api-routes/api-middlewares), [NowResponse](https://nextjs.org/docs/api-routes/response-helpers)) request.
