### ISSUE TITLE
Ream config is broken

### ISSUE THREAD

**Issue by jazoom** [ream/ream#43]
My app was working fine in version v1.0.0-beta.9 but with any later version it is very broken. Yes, I've made the changes for Vue 2.3.

After a lot of hunting I've narrowed down the problem to Ream's config. If pretty much anything is placed in the config the app stops working. I've made a small app to demonstrate. You'll notice that the router doesn't work at all.

https://github.com/jazoom/ream-minimal

However, if you change:

```
const app = ream({
  dev: process.env.NODE_ENV !== 'production',
  html: { template: 'src/index.html' },
  entry: 'src/index.js'
});
```

to:

```
const app = ream({
  dev: process.env.NODE_ENV !== 'production'
});
```

it works just fine.

It also doesn't work if the only thing in there is my extensions to Webpack config.

Actually, while I said it works fine without the config, in this minimal example for some reason the app is still broken due to a "mismatch" between server and client. I can't see where that's coming from in this example (perhaps another bug), but I don't have that problem in my actual full project.

**Comment by egoist** [comment]
You forgot to add `<!--ream-scripts-placeholder-->` to your index.html, that's the place we inject generated assets

**Comment by egoist** [comment]
For some reason I disabled auto `inject` in html-webpack-plugin in rc.2

**Comment by jazoom** [comment]
I wouldn't say "forgot", since I can't find any documentation anywhere about how to make a proper template for Ream. I don't know how I found out about the other three placeholders originally, but there weren't four in the code I got this from.

```
<!--ream-head-placeholder-->
<!--ream-styles-placeholder-->
<!--ream-app-placeholder-->
```

**Comment by egoist** [comment]
Sorry I didn't recall correctly, that's a change in beta.11->rc.2

**Comment by jazoom** [comment]
I'm not sure you should close this, since I just added that in and it still doesn't work.

**Comment by egoist** [comment]
is the router still not working? I've made it work after adding `<!--ream-scripts-placeholder-->` after `<!--ream-app-placeholder-->`

**Comment by jazoom** [comment]
I got it working by copying the exact order in the index.html you provided. Thank you.

**Comment by egoist** [comment]
Glad to hear that 😄
