### ISSUE TITLE
Child metadata does not overwrite parent metadata

### ISSUE THREAD

**Issue by jazoom** [ream/ream#45]
The correct behaviour is described by vue-meta here:
https://github.com/declandewet/vue-meta#how-metainfo-is-resolved

I have created an example of the issue here:
https://github.com/jazoom/ream-minimal

Steps:
1. Right click and select "View page source" -> metadata displays correctly
2. Navigate to `Page 1` (which is a child of `Home`)
3. Right click and select "View page source" -> metadata is duplicated, despite the use of `vmid`

This causes issues with things like Facebook's parsing of OG tags.

I don't know how much of this is a bug with Ream's handling of vue-meta or within vue-meta itself.

**Comment by jazoom** [comment]
So, fixed?

I'm presently trying to narrow down the source of the issue. Are you confident it's within vue-meta? Is that why you closed this?

**Comment by jazoom** [comment]
Great job. That was really fast.

**Comment by egoist** [comment]
You can install `1.0.0-rc.4` to receive updates.

**Comment by egoist** [comment]
The doc is also updated: https://ream.js.org/#/?id=modify-ltheadgt

**Comment by jazoom** [comment]
Ah, I see. It was an issue of Ream using a different name for the attribute. I didn't even consider that. It's probably less confusing this way, keeping it similar to vue-meta.
