### ISSUE TITLE
Context argument is not set in createRouter function for the path "/" 

### ISSUE THREAD

**Issue by ansarizafar** [ream/ream#48]
Context argument is not set in createRouter function for the path "/" 
```
import Vue from 'vue'
import Router from 'vue-router'
import axios from 'axios'

Vue.use(Router)

const createRouter = (context) => {
  console.log(context)
  const router = new Router({
    mode: 'history',
    routes: [{
      path: '/',
      component: () => import('./Home.vue')
    }, {
      path: '/about',
      component: () => import('./About.vue')
    }]
  })
 
  
  if (process.browser) {
    const nprogress = require('nprogress')
    require('nprogress/nprogress.css')

    router.beforeEach((from, to, next) => {
      nprogress.start()
      next()
    })
    router.afterEach(() => {
      nprogress.done()
    })
  }
  
  return router
}

export default { createRouter }

```

**Comment by egoist** [comment]
`context` is only available on server-side.

**Comment by ansarizafar** [comment]
I am logging context on the server side but Context argument is undefined in createRouter function for the path "/" on server-side and context is properly set for other routes.

**Comment by egoist** [comment]
I guess we need to implement a server-side `redirect` method in `context`, using the native `next` function in `beforeEach((to, from, next) => {})` would not work.

**Comment by egoist** [comment]
Hmm, didn't understand you correctly, do you mean something like this? 

```js
router.beforeEach((to, from, next) => {
  if (to.path === '/private') {
    if (process.server && !ctx.req.session) {
      return next('/')
    }
    if (process.browser && !localStorage.getItem('api-key')) {
      return next('/')
    }
  }
  next()
})
```

**Comment by ansarizafar** [comment]
Yes I am trying to do just that with some modifications but I am unable to use custom express server with ream and backpack module. Nuxt works fine with custom express server and backpack [https://github.com/nuxt/express](https://github.com/nuxt/express). Is ream compatible with backpack? Ream is much better than Nuxt If can solve few issues.

**Comment by egoist** [comment]
So is this issue solved already? I can see `context`:

<img width="204" alt="2017-06-11 9 12 35" src="https://user-images.githubusercontent.com/8784712/27011268-b9c82a2c-4eea-11e7-893f-237f446155ff.png">

> Is ream compatible with backpack?

What issues do you run into while using Ream with Backpack? It's just a cli tool to run your node app, so I think it will work fine with Ream. Keep in mind that while using custom express server it's just a normal node app.

**Comment by ansarizafar** [comment]
Yes after updating to rc.5 context is available in createRouter function.
I am using code from template-ream with my own server code
```
const dev = process.env.NODE_ENV !== 'production'
const client = ream({dev: dev, entry: 'src/client/index.js'})
  
client.prepare()
  .then(() => {
    app.get('*', client.getRequestHandler())
this.instance = app.listen(process.env.PORT || 5000,
 (err) => {
if(err) {
   Log.error(`Unable to start API server ${process.pid}.`);
   Event.emit('shutdown')
} else {
          Log.info(`API server ${process.pid} started...`);
    }
});
  })

client.on('ready', () => {
  ream.displayStats(client.stats)
  })
```
Pacjage.json
```
 "start": "backpack build && node ./build/main.js"
```
Build is successful and server is started. Here is the output

![image](https://user-images.githubusercontent.com/5788284/27012192-d2e588c0-4ee4-11e7-8951-cc421f30ff8f.png)

**Comment by ansarizafar** [comment]
It seems that babel-preset-env module is defining node version number as a string and not as a number. Both backback and Neutrino reporting same error. @egoist Could you please suggest a solution.

**Comment by egoist** [comment]
that's weird, we didn't define the node version in babel-preset-env

**Comment by ansarizafar** [comment]
@egoist My project is hosted on glitch.com. If you can share your email then I can send you an invite on glitch.com

**Comment by egoist** [comment]
yup, you can find my email on my profile page

**Comment by ansarizafar** [comment]
@egoist I just sent you an invitation of my project on glitch.com

**Comment by ansarizafar** [comment]
It's working now thanks for the help.
