### ISSUE TITLE
asyncData : Feature request

### ISSUE THREAD

**Issue by ansarizafar** [ream/ream#49]
Please add support for asyncData [https://nuxtjs.org/guide/async-data](https://nuxtjs.org/guide/async-data)

**Comment by egoist** [comment]
I wonder if it's possible to extract that feature from Nuxt.js so every Vue SSR  project can benefit.

/cc @Atinux

**Comment by ansarizafar** [comment]
asyncData is a must have feature and I hope this feature will also be available with Ream SOON.

**Comment by egoist** [comment]
In fact you can use vuex/preFetch to achieve the same thing for now, it's a little more verbose than `asyncData` though.

**Comment by ansarizafar** [comment]
I don't want to use vuex store that is why I have decided to use Nuxt for my current project.

**Comment by egoist** [comment]
Help wanted for this as I can't find an elegant way to implement it 😅 https://github.com/ream/ream/blob/master/docs/guides/preloading-data.md

**Comment by egoist** [comment]
Closed in favor of https://github.com/ream/ream/issues/74
