### ISSUE TITLE
ream generate does not respect router.base configuration

### ISSUE THREAD

**Issue by buhrmi** [ream/ream#54]
In nuxt, setting the `router.base` config in `nuxt.config.js`, will load assets from this base path instead of the origin root. This is important when serving the generated app from a directory.

How to do this with ream?

**Comment by egoist** [comment]
https://ream.js.org/#/api?id=homepage

**Comment by buhrmi** [comment]
nice ... what do you think about copying this setting from the router.base option

**Comment by buhrmi** [comment]
closing this, because it works fine for now. thanks :)

**Comment by egoist** [comment]
we create webpack config before getting the router, so not sure how that would work 😅
