### ISSUE TITLE
[Feature request] Possibility to change dist folder

### ISSUE THREAD

**Issue by hendrysadrak** [ream/ream#57]
I'm trying to achieve vue ssr runned by pm2. Ream would be perfect for my use case but the problem is that i'm trying to run multiple instances of it programmatically so I need multiple `dist` folders. 

My target would be that one instance would write to `dist/in1/`, second one would write to `dist/in2/` and so on.

It would be great to have dist folder configurable through `ream.config.js`

**Comment by egoist** [comment]
Supported in Ream v3 and above, if you have multi project in current directory, like `project1/` `project2/`, you can run the command as follows:

```bash
ream build project1
ream build project2
```

Then the `.ream` directory will be generated to `project1/.ream` and `project2/.ream`.
