### ISSUE TITLE
Ream 2.0 `preFetch`

### ISSUE THREAD

**Issue by FrancosLab** [ream/ream#59]
Using the ream 2.0 beta, and preFetch does not seem to work, am I correct in assuming it is not supported yet? Could not seem to find the appropriate function calls.

**Comment by egoist** [comment]
it's asyncData now

**Comment by FrancosLab** [comment]
Figured it was `asyncData` after going through the docs, however 

`[Vue warn]: Error in beforeCreate hook: "TypeError: Cannot redefine property: $asyncData"`

File in question `https://github.com/ream/ream/blob/fb2730d711d8c2c7fe65e453e7d8dfda03078955/packages/ream-renderer-vue/app/create-app.js`

**Comment by FrancosLab** [comment]
figured out that each top level component needs a name for asyncData function to properly run without the `redefine property` error, also this pull request fixes an error found regarding the setting of the asyncDataStore. https://github.com/ream/ream/pull/60
