### ISSUE TITLE
No Express+Vue (ssr) boilerplate

### ISSUE THREAD

**Issue by Lahori-Jawan** [ream/ream#61]
I want to use ream instead of nuxt because of its flexibility but the problem is I just don't know how to do that... SSR is a thing of server i.e. Expressjs & all docs are related to Vue. So how I am supposed to use that? I can make a simple express server and render some template based on handlebars engine but I don't know how to integrate REAM with experss and without that or easy DX, not many devs are going to use it no matter how flexible/powerful REAM is.

**Comment by cannap** [comment]
from the master 

https://github.com/ream/ream/blob/master/server.js

**Comment by Lahori-Jawan** [comment]
@cannap thanks!
