### ISSUE TITLE
Use UWS with Polka under the hood

### ISSUE THREAD

**Issue by davidbwaters** [ream/ream#69]
I was reading [here](https://github.com/lukeed/polka/blob/master/examples/with-uws) and looking at the [example](https://github.com/lukeed/polka/blob/master/examples/with-uws/index.js), and it looks like using UWS instead of node's native http can double performance.  Could this be implemented under the hood?

**Comment by egoist** [comment]
Your can use Ream programmatically with your custom server:

```js
const { http } = require('uws')
const ream = require('ream')

const app = ream(options)

app.getRequestHandler()
  .then(handler => {
    http.createServer(handler).listen(3000, err => {
      console.log(`> Running on localhost:3000`)
    })
  })
```

**Comment by davidbwaters** [comment]
Cool, thanks.  So I would add this in ream.config.js?

**Comment by egoist** [comment]
Check out this example: https://github.com/ream/ream/blob/master/examples/custom-server-http

**Comment by davidbwaters** [comment]
Awesome, thanks for the support and awesome project(s)!
