### ISSUE TITLE
Can't get root component to work

### ISSUE THREAD

**Issue by chasebank** [ream/ream#70]
Attempting to follow the [root component guide](https://github.com/ream/ream/blob/master/docs/guides/root-component.md) but having some trouble. Everything else seems to be working. This is the main functionality that I find lacking in Nuxt and has me interested in Ream.

Is there an existing complete example set up with this functionality working?

Here's a work in progress https://glitch.com/edit/#!/lily-move

**Comment by egoist** [comment]
Just added an example: https://github.com/ream/ream/blob/master/examples/custom-root-component

**Comment by egoist** [comment]
Closing since it's solved.
