### ISSUE TITLE
Base route ('/') "not found"

### ISSUE THREAD

**Issue by cscomfort** [ream/ream#72]
Having just finished a Vue project, I was curious to explore Ream as alternative to Nuxt--however,  the dev server [`npm run dev`] returns 'not found' when trying to visit the base route. This also seems to occur when testing with your 'custom-root-component' example.

Note that I can successfully render the /about route (About.vue)--and then, interestingly, if I click the link to back to the base route (Home.vue), it renders properly. Yet, if I then refresh the page while on the successfully rendered base route, it again returns 'not found'. In other words, the base route only seems accessible when visiting it from a previously rendered route.

Could this have something to do with my configuration, or the use of the custom root component?

Currently running Node v8.10.0. Thanks in advance for any assistance.

```
.
|-- node_modules
|-- views
|   |-- About.vue
|   |-- Home.vue
|   |-- App.vue
|-- index.js
|-- package.json
```

**package.json**
```javascript
{
  "name": "ream-test",
  "scripts": {
    "build": "ream build",
    "start": "ream start",
    "dev": "ream dev"
  },
  "dependencies": {
    "ream": "^3.0.0-rc.5"
  }
}
```

**index.js**
```javascript
import Vue from 'vue'
import Router from 'vue-router'

Vue.use(Router)

export default {
  root: () => import('./views/App.vue'),
  router: () => new Router({
    mode: 'history',
    routes: [{
      path: '/',
      component: () => import('./views/Home.vue')
    }, {
      path: '/about',
      component: () => import('./views/About.vue')
    }]
  })
}
```

**App.vue**
```html
<template>
  <div>
    <header>Ream Test</header>
    <router-view />
  </div>
</template>
```

**Home.vue**
```html
<template>
  <div>
    <h1>Hello, World.</h1>
    <p><router-link to="about">About</router-link></p>
  </div>
</template>
```

**About.vue**
```html
<template>
  <div>
    <h1>About the Ream Project...</h1>
    <p><router-link to="/">Home</router-link></p>
  </div>
</template>
```

**Comment by egoist** [comment]
Related to https://github.com/lukeed/matchit/issues/7

**Comment by egoist** [comment]
It should be fixed now by reinstalling Ream.
