### ISSUE TITLE
Prefetch data for route components

### ISSUE THREAD

**Issue by egoist** [ream/ream#74]
Currently we have [getInitialData](https://github.com/ream/ream/blob/master/docs/guides/preloading-data.md) but it does not inject data or props to relevant route component, hopefully we can implement a _real_ `getInitialData` which injects resolved object to component data or `getInitialProps` which injects props instead.

`getInitialData`:

```js
export default {
	async getInitialData() {
		return { count: 0 }
	},
	render() {
		return <button>{this.count /* this.$data.count */}</button>
	}
}
```

`getInitialProps`:

```js
export default {
	async getInitialProps() {
		return { count: 0 }
	},
	props: ['count']
	render() {
		return <button>{this.count /* this.$props.count */}</button>
	}
}
```

If it's possible to have `getInitialProps` then we don't need to implement `getInitialData`

---

Refs:

- [getInitialProps](https://github.com/zeit/next.js/#fetching-data-and-component-lifecycle) in Next.js
- [asyncData](https://nuxtjs.org/api/) in Nuxt.js

**Comment by VsevolodTrofimov** [comment]
It seems like HOC is the only way to do this, but they are ugly in vue. 😕

**Comment by iFwu** [comment]
很简单啊，我自己写的一个Vue SSR框架就实现了（基于vue hacknews 2.0那个），有空写个PR。

**Comment by egoist** [comment]
https://ream.js.org/guide/data-prefetching.html
