### ISSUE TITLE
If ream.config.js throws it is silently ignored

### ISSUE THREAD

**Issue by IlyaSemenov** [ream/ream#80]
## Steps to reproduce

Create `ream.config.js`:

```
const path = require('path')
module.exports = {
  entry: 'myentry.js',
  plugins: [
    require('no/such/package')()
  ]
}
```

Run `npm-run ream dev`

## Expected result

Somehow `Error: Cannot find module 'no/such/package'` is printed.

## Actual result

`ream.config.js` is ignored altogether.

**Comment by egoist** [comment]
It's a bug in a dependency, should be fixed if you re-install ream.

**Comment by IlyaSemenov** [comment]
Thanks. `yarn remove ream && yarn add ream` fixed it indeed.
