### ISSUE TITLE
Client bundle should be named client.[hash].js

### ISSUE THREAD

**Issue by IlyaSemenov** [ream/ream#82]
Client bundle is currently put into `.ream/client/client.js`. This isn't a feasible default for production; users will receive all sort of false bug reports because clients will be using outdated versions.

I believe `config.output.filename` should be set to `'[name].[hash:8].js'` by default, at least in production. (I know it can be easily changed with a plugin, it's just a suggestion to change the default).

**Comment by egoist** [comment]
The assets files generated by webpack are cached by service worker, so they will be automatically updated 😄

But adding a hash should be good too, mind a PR?
