### ISSUE TITLE
mini-css-extract-plugin is mentioned in dependencies but not used

### ISSUE THREAD

**Issue by IlyaSemenov** [ream/ream#83]
mini-css-extract-plugin is mentioned in dependencies but is not used. I believe it should be used (in production) but if not it probably should be removed from dependencies?

**Comment by egoist** [comment]
will remove it for now, but I plan to add proper css extraction support soon, ideally we should only inline component-scoped css but extract those shared css files.

**Comment by IlyaSemenov** [comment]
I ended up with a plugin like that:

```js
const MiniCssExtractPlugin = require('mini-css-extract-plugin')

module.exports = function plugin (options) {
  options = Object.assign({
    filename: '[name].[hash:8].css',
    chunkFilename: '[id].[hash:8].css'
  }, options)
  return {
    name: 'css-extract',
    apply (ream) {
      if (!ream.options.dev) {
        ream.chainWebpack(config => {
          config.plugin('css-extract').use(MiniCssExtractPlugin, [options])
          for (const lang of ['css', 'scss', 'sass', 'less', 'stylus']) {
            for (const oneOf of ['normal', 'modules']) {
              config.module.rule(lang).oneOf(oneOf).use('vue-style-loader').loader(MiniCssExtractPlugin.loader).options()
            }
          }
        })
      }
    }
  }
}
```

**Comment by egoist** [comment]
Added in `3.2.0`

**Comment by IlyaSemenov** [comment]
Did you not include `OptimizeCSSAssetsPlugin` on purpose? In my project I have CSS coming from `webfonts-loader`, with the new setup that CSS is not minified. Also, CSS coming from different components are separated with 2 line breaks (not that it's too bad...).
