### ISSUE TITLE
Migrating existing application

### ISSUE THREAD

**Issue by davestewart** [ream/ream#87]
Hey,

This looks like a great project!

It also looks much easier to migrate an existing app vs Nuxt, because you're changing the code in files, rather than moving files to directories, creating new routing folders, and changing the overall architecture.

Is this a correct assumption? (I'm no Nuxt expert).

**Comment by egoist** [comment]
Yep 👌

**Comment by davestewart** [comment]
You win the award for quickest ticket response ever.

Thanks! I'll jump right in :)
