### ISSUE TITLE
CSS modules broke in Ream 3.2

### ISSUE THREAD

**Issue by IlyaSemenov** [ream/ream#88]
```vue
<template>
  <div :class="$style.blue">Hello Ream!</div>
</template>

<style module>
.blue { color: blue; }
</style>
```

This code works in Ream 3.1 (dev & production), Ream 3.2 (dev) but not in Ream 3.2 (production). In Ream 3.2 production, CSS class **is** generated and saved into `client.hash.css`, but HTML code is `<div>Hello Ream!</div>`.

Tested on a completely fresh install, on a clean test project with no setting overrides. `yarn remove ream; and yarn add ream@3.1` makes it blue again.

**Comment by egoist** [comment]
I noticed that only happens after I added extraction support, not sure how it happens though

**Comment by IlyaSemenov** [comment]
I have been running 3.1 with css-extract (I pasted my exact plugin in #83) and it worked fine. Just FYI.

**Comment by IlyaSemenov** [comment]
I bisected it to this line: https://github.com/ream/ream/blob/35f8fcd2bc1066f28649bfe25a8f0f1ea0542daf/lib/webpack/webpack.config.base.js#L220

If set to `css-loader` unconditionally, the problem is gone.

**Comment by IlyaSemenov** [comment]
Oh, you're faster 👍
