### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by redxtech** [ream/ream#97]
I'm very interested in using this project when it's released!

Is there a roadmap or something similar that shows how this project is progressing?

**Comment by ThomOrlo** [comment]
https://twitter.com/_egoistlily/status/1353370388386865153
https://github.com/ream/ream/tree/vite
👀

**Comment by egoist** [comment]
I plan to release it someday in late February.

**Comment by egoist** [comment]
Released https://twitter.com/_egoistlily/status/1365310934655246347
