### ISSUE TITLE
Ream doesn't work with a Poi Typescript project.

### ISSUE THREAD

**Issue by x1024** [ream/ream#99]
In Poi, it was easy to add typescript support by using the builtin "@poi/plugin-typescript" plugin.  
Ream doesn't seem to have that supported yet, but I'd like to get it working so that I can convert my Poi project to Ream.

What should I look at in order to convert the Poi plugin to work with Ream?

**Comment by IlyaSemenov** [comment]
I use this plugin for typescript:

```js
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin')

module.exports = function plugin (options) {
  options = Object.assign({
    appendTsSuffixTo: [/\.vue$/],
    transpileOnly: true
  }, options)

  return {
    name: 'typescript',
    apply (ream) {
      ream.chainWebpack((config, { type }) => {
        config.module.rule('js').test(/\.(jsx?|tsx?)$/).use('ts-loader').after('babel-loader').loader('ts-loader').options(options)
        config.module.rule('vue').use('vue-loader').tap(options => {
          options = options || {}
          options.loaders = options.loaders || {}
          options.loaders.ts = {
            loader: 'ts-loader',
            options
          }
        })
        if (type === 'server') {
          // Only run for server compiler to prevent duplicate errors
          config.plugin('ts-checker').use(ForkTsCheckerWebpackPlugin, [{ vue: true }])
        }
      })
    }
  }
}
```

then in `ream.config.js`:

```js
module.exports = {
  plugins: [
    require('./src/ream-plugins/typescript')()
  ]
}
```

I am not entirely surely it's a fully appropriate approach, but generally it works. For the record, I'm not happy with these:
- `if (type === 'server')` bugs me a little;
- I'm not sure if `ForkTsCheckerWebpackPlugin` is supposed to be used in production;
- I wanted to use the `merge` function inside the options tap as recommended in [webpack-chain README](https://github.com/mozilla-neutrino/webpack-chain#config-module-rules-uses-loaders-modifying-options), but I didn't figure out how to import it.

@egoist do you think it makes sense to include this as a built-in plugin and enable with `typescript: true` in `ream.config.js`? It's not clear how to define dependencies in this case. Or rather publish it as `ream-typescript` (perhaps along with typings for ream API, `getInitialData` etc.)?

**Comment by IlyaSemenov** [comment]
I published [ream-typescript](https://github.com/IlyaSemenov/ream-typescript).

**Comment by IlyaSemenov** [comment]
I use `ream-typescript` in two projects, it's not finished but usable. If you have specific issues, please elaborate.
